stages:
  - plan
  - apply

variables:
  TF_VAR_region: "us-west-2"
  TF_VAR_vpc_cidr_block: "10.0.0.0/16"
  TF_VAR_ec2_instance_type: "t2.micro"
  TF_VAR_ami_id: "ami-0abcdef1234567890"
  TF_VAR_db_username: "devuser"
  TF_VAR_db_password: "devpassword"

before_script:
  - apt-get update && apt-get install -y wget unzip
  - wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
  - unzip terraform_1.0.0_linux_amd64.zip
  - mv terraform /usr/local/bin/

terraform_init:
  stage: plan
  script:
    - terraform init
    - terraform validate
  only:
    - dev
    - staging
    - prod

terraform_plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  only:
    - dev
    - staging
    - prod

terraform_apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  only:
    - dev
    - staging
    - prod
